export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE'
export const DELETE_MOVIES_SUCCES = 'DELETE_MOVIES_SUCCES'
export const LOAD_FILTER_SUCCESS = 'DELETE_MOVIES_SUCCES'